### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by edysegura** [rodrigofaria/trabalho_dm107#3]
It would be nice to have some instructions in **README.md** to explain how to use the API's that you guys have implemented.

![image](https://cloud.githubusercontent.com/assets/5324414/10883684/c4728620-815a-11e5-8e15-3c6e2c08000f.png)

**Comment by rodrigofaria** [comment]
@afrans commit the fix for this issue!

**Comment by edysegura** [comment]
I saw that! It is now awesome!
