### ISSUE TITLE
Wrong tab title

### ISSUE THREAD

**Issue by edysegura** [rodrigofaria/trabalho_dm107#5]
I believe that tab title is not the right one for this swagger project specification:

![screenshot from 2015-11-03 01 38 38](https://cloud.githubusercontent.com/assets/5324414/10900849/1ea8a7de-81cc-11e5-845d-a6f0ef76fc0d.png)

**Comment by rodrigofaria** [comment]
Fix this isse now...and we will update the AWS tomorrow morning.
