### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by edysegura** [rodrigofaria/trabalho_dm107#7]
How can we obtain the token? Would be nice to have an instruction at **README.md** and a specification on **swagger** as well.

![token](https://cloud.githubusercontent.com/assets/5324414/10900965/ec670eee-81cd-11e5-9425-d0055e8a0be7.png)

**Comment by rodrigofaria** [comment]
Added README

**Comment by edysegura** [comment]
The documentation is awesome now! Thank you guys!
